### ISSUE TITLE
FEATURE REQUEST - Operational metadata

### ISSUE THREAD

**Issue by falkorichter** [sparkfun/SparkFun_DataLogger#18]
I'm wondering if it would be possible to send metadata about the logger with every data request

something like this 
```
"General"  : {
   [...]
   "uptime": 123456,
   "wifi_wrssi" : -56,
   "wifi_ssid" : "homeWifi"
}
```
this would enable someone to build some operational excellence and monitor the performance and stability of the device.

[update] updated to use the `General` key in the JSON [/update]

**Comment by gigapod** [comment]
This is a great idea - we'll get in our backlog and also see if any other information might be relevant ...

**Comment by falkorichter** [comment]
I enabled some settings and saw the `General` payload activated. I updated the inital request.
