### ISSUE TITLE
Parameter/Character limit

### ISSUE THREAD

**Issue by MarekJar** [sparkfun/SparkFun_DataLogger#8]
Hello

There seems to be some kind of parameter or character limit for the output.

We were experimenting with 6 modules on the I2C bus, but for some reason when adding modules, the last parameters are left out of the message, at least in the JSON format.

Some modules have many parameters, which causes some parameters to be left out from the output, even from the on-board sensors.
Even adding timestamp to the message causes loss of at least 1 parameter output.

Would it be possible to remove this limit or increase the number of parameters in the output to some larger number?

Best regards,

Marek J.

**Comment by gigapod** [comment]
Hi @MarekJar,

The internal JSON buffer is hard coded to 1600. Obviously too conservative. 

We're making this a user accessible preference.  This will be in the next firmware update scheduled for mid November.

**Comment by gigapod** [comment]
This is now a user configurable option in [version 1.1.0](https://github.com/sparkfun/SparkFun_DataLogger/releases/tag/v01.00.01)
