### ISSUE TITLE
Duplicate configuration values?

### ISSUE THREAD

**Issue by MarekJar** [sparkfun/SparkFun_DataLogger#9]
Greetings,

 In the Serial configuration interface, what is the difference between "/Settings/Application Settings/Output" and "/Settings/Logger/Output"?

Do they serve a separate function or is it simply a duplicate?

Best regards,

Marek J.

**Comment by gigapod** [comment]
These are the same. The /Settings/Logger/Output properties are basically *aliases* to the settings in Application Settings". 

The thought was that some users would look under the Logger settings and not application settings ...
